Update README.md
etiennemartin/CodeReviewTesting pull request #3
Opened 2017-03-02 19:51 UTC by sebmartin

This sucks

2017-03-02 19:51 UTC, sebmartin commented
....................../´¯/) 
....................,/¯../ 
.................../..../ 
............./´¯/'...'/´¯¯`·¸ 
........../'/.../..../......./¨¯\ 
........('(...´...´.... ¯~/'...') 
.........\.................'...../ 
..........''...\.......... _.·´ 
............\..............( 
..............\.............\...

2017-03-02 19:53 UTC, sebmartin commented
ping @etiennemartin

2017-03-03 14:49 UTC, etiennemartin requested changes
This is amazing.  You're so talented.  I wish I was as good at writing README's as you are.  You're my hero.

2017-03-03 14:49 UTC, etiennemartin commented on README.md
> +This repo fucking sucks
Missing additional line after this fool!

2017-03-06 19:01 UTC, closed without merging